# Configuration for query prediction experiment
# Adjust parameters as needed for your specific use case

experiment:
  name: 'default_experiment'
  prediction_gap: 1
  random_seed: 42
  sessions_limit: null  # null for all sessions, integer for limited number

discretization:
  enabled: true
  method: 'equal_width'  # Options: equal_width, equal_freq, kmeans
  bins: 3  # Reduced from 5 to reduce encoded column explosion
  save_params: true
  params_path: 'discretization_params.pkl'

association_rules:
  enabled: true
  min_support: 0.3  # Increased to reduce rule explosion on large datasets
  metric: 'confidence'  # Options: support, confidence, lift, leverage, conviction
  min_threshold: 0.8  # Increased threshold for better quality rules
  max_len: 3  # Limit rule length to prevent exponential explosion

summaries:
  enabled: true
  desired_size: 5  # Number of summaries to generate
  weights: null  # Custom weights for attributes, null for equal weights

interestingness:
  enabled: true
  measures:
    - 'variance'
    - 'simpson'
    - 'shannon'
    - 'total'

recommendation:
  enabled: true
  method: 'hybrid'  # Options: association_rules, summaries, hybrid
  recommender_type: 'interestingness'  # Options: dummy, random, clustering, interestingness, query_expansion
  mode: 'top_k'  # Options: top_k, top_quartile, percentage
  top_k: 10  # Number of tuples to recommend (for top_k mode)
  percentage: 0.1  # Percentage of tuples to recommend (for percentage mode)
  score_threshold: 0.5  # Minimum score for recommendations

# Configuration for different recommender types
clustering:
  n_clusters: null  # Number of clusters, null for auto-determination
  random_state: 42
  max_iter: 300
  n_init: 10

random:
  random_seed: 42

# NEW: Query Expansion Recommender Configuration
query_expansion:
  # Enable/disable different expansion strategies
  enable_range_expansion: true
  enable_constraint_relaxation: true
  enable_join_exploration: true
  enable_column_expansion: true
  enable_similarity_search: true
  
  # Budget management to control computational cost
  budget:
    max_queries: 5              # Maximum number of expansion queries to execute
    max_execution_time: 30.0    # Maximum total time in seconds
    max_results_per_query: 1000 # Maximum results per individual query
  
  # Expansion parameters
  range_expansion_factor: 0.2   # How much to expand numeric ranges (20%)
  min_confidence_threshold: 0.3 # Minimum confidence for candidate queries
  max_query_complexity: 5       # Maximum complexity score for generated queries

evaluation:
  metrics:
    - 'accuracy'
    - 'overlap'
    - 'jaccard'
    - 'precision'
    - 'recall'
    - 'f1'
  jaccard_threshold: 0.5  # Threshold for considering tuples similar in Jaccard similarity
  column_weights: null  # Custom weights for columns in similarity calculation

output:
  save_results: true
  results_dir: 'experiment_results'
  save_format: 'json'  # Options: pkl, csv, json
